version: "3.8"

# replica set for mongo

services:
  mongo:
    image: mongo:7.0
    command: --replSet rs0 --bind_ip_all
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ecf052ef4ae6c66033f166054d7f9deb47929da556071384
    volumes:
      - ./data:/data/db
    networks:
      - mongo

  mongo2:
    image: mongo:7.0
    command: --replSet rs0 --bind_ip_all
    container_name: mongo2
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ecf052ef4ae6c66033f166054d7f9deb47929da556071384
    volumes:
      - ./data2:/data/db
    networks:
      - mongo

  mongo3:
    image: mongo:7.0
    command: --replSet rs0 --bind_ip_all
    container_name: mongo3
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ecf052ef4ae6c66033f166054d7f9deb47929da556071384
    volumes:
      - ./data3:/data/db
    networks:
      - mongo

networks:
  mongo:
    driver: bridge

